ENV_PKG_PATH = $(ECE745_PROJECT_HOME)/verification_ip/environment_packages/i2cmb_env_pkg
comp_i2cmb_env_pkg:
	vlog +incdir+$(ECE745_PROJECT_HOME)/verification_ip/ncsu_pkg +incdir+$(ECE745_PROJECT_HOME)/verification_ip/interface_packages/wb_pkg/src +incdir+$(ECE745_PROJECT_HOME)/verification_ip/interface_packages/i2c_pkg +incdir+$(ECE745_PROJECT_HOME)/verification_ip/environment_packages/i2cmb_env_pkg $(ENV_PKG_PATH)/i2cmb_env_pkg.sv
